
version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
