
version: "3.8"
services:
  prune_postgres:
      image: docker:latest
      entrypoint: >
        sh -c "
        docker stop postgres_container &&
        docker rm postgres_container
        "
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  prisma:
      image: node
      container_name: prisma-container
      working_dir: /app
      volumes:
        - .:/app
      command: ["npx", "prisma", "generate"]
      depends_on:
        - postgres
      environment:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mydb"

